# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
    #https://github.com/marketplace/actions/mvn-cmd
    #https://github.com/marketplace/actions/action-maven-deploy
    jobPublish:      
      name: Job generating setting for mv deploy
      #needs: pipeline
      runs-on: ubuntu-20.04
      steps:
        - name: Generate Settings	
          uses: qcastel/github-actions-maven/actions/maven@master
          with:
            maven-local-repo-path: ${{ secrets.JFROG_OSS_REPO_SNAPSHOTS }}
            maven-repo-server-id: snapshots
            maven-repo-server-username: ${{ secrets.JFROG_OSS_REPO_USER }}
            maven-repo-server-password: ${{ secrets.JFROG_OSS_REPO_PASS }}
            #maven-args: "./mvnw -ntp package deploy -Pprod -DskipTests"
        - name: Publish artefact
          run: |
            cat ~/.m2/settings.xml
            mvn -ntp package deploy -Pprod -DskipTests
